### PR TITLE
[ios] Add tests, fix bugs & other improvements

### LINKED ISSUE #169: Problems occured when calling TrackPlayer.remove() method
on the iOS, after i removed the track using `TrackPlayer.remove()` method, the system would play the track again automatically, and also I would find related codes in the link below [url](https://github.com/react-native-kit/react-native-track-player/blob/dev/ios/RNTrackPlayer/Logic/MediaWrapper.swift#L102-L122) . But the same situation didnot happen on Android.
I feel confused. Does this feature be removed on the iOS or added to the Android? I think this logic should be handled by the user.

### LINKED ISSUE #170: insertBeforeId doesn't seem to work?
I'm trying to implement a "play next" functionality that inserts a song into the queue as the next-in-line track. I've been trying this way:

```
addNext = function(song) {
    var mediaInfo = {
        id: song.id.toString(),
        url: song.url,
        title: song.title,
        artist: song.artist,
        artwork: resizeArtwork(song.artwork),
        album: 'Indie Shuffle',
    }
    // Use the mobx "store" to figure out the id of the song we're inserting before
    var position = store.position + 1 // current track position within queue + 1
    var playlist = store.playlist // a duplicate of the queue, saved as a mobx object
    var second = store.playlist[position]
    var id = second ? second.id.toString() : null
    console.log(id,typeof(id)) // returns the correct "next" id as a "string"
    TrackPlayer.add([mediaInfo],id) // The song gets added to the very end
}
```
Stumped.

### PR DESCRIPTION
**Pull request by dcvz**
- [x] Fixes #170 
- [x] Fixes #169 
- [x] Adds `removeUpcomingTracks` method
- [x] Adds `getQueue` method which will provide the original objects passed
- [x] Adds improvements to iOS reconnection strategy
- [x] Adds test on iOS to help keep stability and find bugs
- [x] Updates example to use media center controls + android notification
- [x] Fix bugs in adding and removing tracks

### CODE REVIEW

File: example/ios/exampleTests/RNTrackPlayerTest.swift [hunk 1]
```diff
@@ -0,0 +1,572 @@
...
+                    let castedQueue = queue as? [[String: Any]]
+                    expect(castedQueue).to(haveCount(1))
+                }) { _ in }
+                
+                module.getCurrentTrack(resolve: { trackId in
+                    expect(trackId as? String).to(equal("test-correct-2"))
+                }) { _ in }
+            }
+            
+            it("stops playback if current track is last in queue and is removed") {
```
Comment (dcvz) [inline example/ios/exampleTests/RNTrackPlayerTest.swift]: @Guichaguri another note

File: example/ios/exampleTests/RNTrackPlayerTest.swift [hunk 2]
```diff
@@ -0,0 +1,572 @@
...
+                module.getState(resolve: { state in
+                    expect(state as? String).to(equal(MediaWrapper.PlaybackState.stopped.rawValue))
+                }) { _ in }
+                
+                module.getCurrentTrack(resolve: { trackId in
+                    expect(trackId).to(beNil())
+                }) { _ in }
+            }
+            
+            it("continues to next track if current track is removed and it wasn't the last") {
```
Comment (dcvz) [inline example/ios/exampleTests/RNTrackPlayerTest.swift]: @Guichaguri

File: lib/index.js [hunk 3]
```diff
@@ -143,7 +143,9 @@ module.exports.registerEventHandler = registerEventHandler;
 module.exports.add = add;
 module.exports.remove = remove;
 module.exports.skip = TrackPlayer.skip;
+module.exports.getQueue = TrackPlayer.getQueue;
```
Comment (dcvz) [inline lib/index.js]: @Guichaguri added this one. It will return the whole queue. It'll return the same object that was passed in. iOS already saves the original object.

File: lib/index.js [hunk 4]
```diff
@@ -143,7 +143,9 @@ module.exports.registerEventHandler = registerEventHandler;
...
 module.exports.skipToNext = TrackPlayer.skipToNext;
+module.exports.clearQueue = TrackPlayer.clearQueue;
```
Comment (dcvz) [inline lib/index.js]: Added this one as well. It will clear the queue but not stop the currently playing track.

File: example/ios/exampleTests/RNTrackPlayerTest.swift [hunk 5]
```diff
@@ -0,0 +1,571 @@
...
+                module.play()
+                module.skipToNext(resolve: { _ in }) { _ in }
+                
+                module.skipToPrevious(resolve: { _ in }) { _ in fail() }
+                module.getCurrentTrack(resolve: { trackId in
+                    expect(trackId as? String).to(equal("test-correct"))
+                }) { _ in }
+            }
+            
+            it("rejects if no tracks before current one and stops playback") {
```
Comment (dcvz) [inline example/ios/exampleTests/RNTrackPlayerTest.swift]: @Guichaguri note that it will stop playback on failure

File: example/ios/exampleTests/RNTrackPlayerTest.swift [hunk 6]
```diff
@@ -0,0 +1,571 @@
...
+                module.add(trackDicts: [correctTrack, anotherCorrectTrack], before: nil, resolve: { _ in }) { _ in }
+                module.play()
+                
+                module.skipToNext(resolve: { _ in }) { _ in fail() }
+                module.getCurrentTrack(resolve: { trackId in
+                    expect(trackId as? String).to(equal("test-correct-2"))
+                }) { _ in }
+            }
+            
+            it("rejects if no more tracks left to play and stops playback") {
```
Comment (dcvz) [inline example/ios/exampleTests/RNTrackPlayerTest.swift]: @Guichaguri note it stops playback on failure

**Comment by dcvz** [comment]
@Guichaguri I think it'd be good if you read through the test cases. Will help align Android to a standard ⭐️ Also it'd be cool if you could implement the two new methods on Android.

File: android/build.gradle [hunk 7]
```diff
@@ -42,62 +46,54 @@ android {
...
-        provided 'com.danikula:videocache:2.7.0'
+        compileOnly 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.7.1'
     }
 
-    // Make sure we're using at least the support library 23.2.0, not 23.0.1
-    compile 'com.android.support:appcompat-v7:23.2.0'
+    implementation "com.android.support:support-compat:$supportVersion"
+    implementation "com.android.support:appcompat-v7:$supportVersion"
+    implementation "com.android.support:support-media-compat:$supportVersion"
+    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
```
Comment (Guichaguri) [inline android/build.gradle]: I've been thinking a lot about using Kotlin in this project. Although it does have a few advantages, you still need to bundle a few dependencies just to use it. I don't think it's worth it in React Native, as you're already bundling a lot of native and JS code

**Comment by alangumer** [comment]
please update the package in npm :)

**Comment by dcvz** [comment]
@alangumer 0.2.4 has now been released! 🎉
